controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

index:
    path: /
    controller: App\Controller\TaskController::index
    methods: GET

create_task:
    path: /task
    controller: App\Controller\TaskController::createTask
    methods: POST

get_tasks:
    path: /task/{id}
    controller: App\Controller\TaskController::getTask
    methods: GET

list_tasks:
    path: /tasks
    controller: App\Controller\TaskController::listTasks
    methods: GET

update_tasks:
    path: /task/{id}
    controller: App\Controller\TaskController::updateTask
    methods: PATCH

delete_task:
    path: /task/{id}
    controller: App\Controller\TaskController::deleteTask
    methods: DELETE

toggle_done:
    path: /task/{id}/toggle-done
    controller: App\Controller\TaskController::toggleDone
    methods: POST
